/**:
    ros__parameters:
        image_transport: raw
        family: 36h11
        # size: 0.05              # 10 cm tag edge size in meters
        max_hamming: 0

        detector:
            threads: 1
            decimate: 1.0       # full resolution for better detection
            blur: 0.0
            refine: True
            sharpening: 0.25
            debug: False

        pose_estimation_method: "pnp"

        tag:
            ids: [69]
            frames: [apriltag_69]
            sizes: [0.08]
